services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cps-shipping-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStr0ngPassw0rd1
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: